# Generated by Django 5.2.5 on 2025-09-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('pending_payment', 'Pending Payment'), ('rescheduled', 'Rescheduled')], default='pending_payment', max_length=20),
        ),
    ]
