# Generated by Django 5.2.5 on 2025-09-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='zoho_booking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoho_meeting_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
