# Generated by Django 5.2.5 on 2025-09-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_to',
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(default=9482140703, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='staff_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
