# Generated by Django 5.2.5 on 2025-09-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
