# Generated by Django 5.2.5 on 2025-09-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_doctor_last_assigned_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='last_assigned_date',
            new_name='last_assigned',
        ),
    ]
