# Generated by Django 5.2.5 on 2025-09-22 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_rename_last_assigned_date_doctor_last_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='calendar_id',
            new_name='zoho_calendar_id',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='staff_id',
            new_name='zoho_staff_id',
        ),
    ]
