# Generated by Django 5.2.5 on 2025-09-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_rename_calendar_id_doctor_zoho_calendar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
