# Generated by Django 5.2.5 on 2025-09-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='max_patients',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
