# Generated by Django 5.2.5 on 2025-09-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
