# Generated by Django 5.2.5 on 2025-09-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='category',
            field=models.CharField(choices=[('core', 'Core - Psychiatrist Led Package Deals'), ('balance', 'Balance - Psychologist Led Package Deals')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='category',
            field=models.CharField(choices=[('core', 'Core - Psychiatrist Led'), ('balance', 'Balance - Psychologist Led'), ('couples', 'Couples Sessions')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
