# Generated by Django 5.2.5 on 2025-09-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_packageplan_category_sessionplan_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packageplan',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=10), max_digits=10),
        ),
    ]
