# Generated by Django 5.2.5 on 2025-09-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_packageplan_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageplan',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
