# Generated by Django 5.2.5 on 2025-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_packageplan_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplan',
            name='zoho_service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
