# Generated by Django 5.2.5 on 2025-09-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_session_timings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='preferred_time_of_day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
