# Generated by Django 5.2.5 on 2025-09-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('users', '0004_remove_patientprofile_preferred_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctors.doctor'),
        ),
    ]
