# Generated by Django 5.2.5 on 2025-09-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_patientprofile_assigned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='reason_for_visit',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
