# Generated by Django 5.2.5 on 2025-09-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_patientprofile_reason_for_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='reason_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
