# Generated by Django 5.2.5 on 2025-09-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_patientprofile_reason_for_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
