# Generated by Django 5.2.5 on 2025-09-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_patientprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
