# Generated by Django 5.2.5 on 2025-09-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_patientprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='updated_at',
        ),
    ]
