# Generated by Django 5.2.5 on 2025-09-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_patientprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
